#!/usr/bin/env node
'use strict';
/**
 * Main file, use this to run the server:
 * node ranvier [options]
 *
 * Options:
 *   -v Verbose loggin
 *   --port Port to listen on
 *   --locale Locale to act as the default
 *   --save Minutes between autosave
 *   --respawn Minutes between respawn
 */

//TODO: Refactor

// local
const Server = require('./src/Server');

  // third party
const pe        = require('pretty-error').start();

pe.skipNodeFiles();

// Set debug variable
process.env['NODE_DEBUG'] = 'net';

// START IT UP!
let server = new Server();

server.init();

// vim: set syn=javascript :
